#!/bin/bash

#number of threads:
for t in 1 2 4 6 8
do
    #echo NUMT=$t
    #number of subdivisions:
    for s in 32000 64000 128000 256000 512000 1024000 2048000 3072000 4096000
    do
        #echo NUMS=$s
        g++ -DNUMTRIALS=$s -DNUMT=$t montecarlo.cpp -o montecarlo -lm -fopenmp
        ./montecarlo
    done
done
