#!/bin/bash

#number of threads:
for t in 8 16 32 64 128 256 512
do
    #echo NUMT=$t
    #number of subdivisions:
    for s in 1 2 4 8 16 32 64
    do
        #echo NUMS=$s
        icpc -DNMB=$s -DLOCAL_SIZE=$t first.cpp -o first /usr/lib64/libOpenCL.so -lm -fopenmp
        ./first
    done
done
