#!/bin/bash

#number of threads:
for t in 32 64 128 256
do
    #echo NUMT=$t
    #number of subdivisions:
    for s in 1 2 4 8 16 32 64
    do
        #echo NUMS=$s
        icpc -DNMB=$s -DLOCAL_SIZE=$t second.cpp -o second /usr/lib64/libOpenCL.so -lm -fopenmp
        ./second
    done
done
